-- MySQL Script generated by MySQL Workbench
-- Thu Oct 26 22:44:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Carteira_de_Vacinação
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Carteira_de_Vacinação
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Carteira_de_Vacinação` DEFAULT CHARACTER SET utf8 ;
USE `Carteira_de_Vacinação` ;

-- -----------------------------------------------------
-- Table `Carteira_de_Vacinação`.`Fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carteira_de_Vacinação`.`Fabricante` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carteira_de_Vacinação`.`Vacinador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carteira_de_Vacinação`.`Vacinador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carteira_de_Vacinação`.`Estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carteira_de_Vacinação`.`Estabelecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carteira_de_Vacinação`.`Vacina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carteira_de_Vacinação`.`Vacina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `lote` VARCHAR(45) NOT NULL,
  `data_aplicacao` DATE NOT NULL,
  `id_fabricante` INT NOT NULL,
  `id_vacinador` INT NOT NULL,
  `id_estabelecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vacina_Fabricante_idx` (`id_fabricante` ASC) VISIBLE,
  INDEX `fk_Vacina_Vacinador1_idx` (`id_vacinador` ASC) VISIBLE,
  INDEX `fk_Vacina_Estabelecimento1_idx` (`id_estabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_Vacina_Fabricante`
    FOREIGN KEY (`id_fabricante`)
    REFERENCES `Carteira_de_Vacinação`.`Fabricante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacina_Vacinador1`
    FOREIGN KEY (`id_vacinador`)
    REFERENCES `Carteira_de_Vacinação`.`Vacinador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vacina_Estabelecimento1`
    FOREIGN KEY (`id_estabelecimento`)
    REFERENCES `Carteira_de_Vacinação`.`Estabelecimento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
