-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 21:36:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Hospital` DEFAULT CHARACTER SET utf8 ;
USE `Hospital` ;

-- -----------------------------------------------------
-- Table `Hospital`.`Medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Medico` (
  `CRM` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Especialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CRM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Paciente` (
  `Codigo_Paciente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Sobrenome` VARCHAR(45) NULL,
  PRIMARY KEY (`Codigo_Paciente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Hospital`.`Atendimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Hospital`.`Atendimento` (
  `idAtendimento` INT NOT NULL,
  `CRM_Medico` VARCHAR(45) NOT NULL,
  `Codigo_Paciente` INT NOT NULL,
  `Gravidade_Paciente` VARCHAR(45) NULL,
  PRIMARY KEY (`idAtendimento`),
  INDEX `fk_Atendimento_Paciente_idx` (`Codigo_Paciente` ASC) VISIBLE,
  INDEX `fk_Atendimento_Medico1_idx` (`CRM_Medico` ASC) VISIBLE,
  CONSTRAINT `fk_Atendimento_Paciente`
    FOREIGN KEY (`Codigo_Paciente`)
    REFERENCES `Hospital`.`Paciente` (`Codigo_Paciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atendimento_Medico1`
    FOREIGN KEY (`CRM_Medico`)
    REFERENCES `Hospital`.`Medico` (`CRM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
