-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 21:26:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Exemplo1_Avião
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Exemplo1_Avião
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Exemplo1_Avião` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Exemplo1_Avião` ;

-- -----------------------------------------------------
-- Table `Exemplo1_Avião`.`Piloto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exemplo1_Avião`.`Piloto` (
  `Num_Registro` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Data_Validade` DATE NOT NULL,
  PRIMARY KEY (`Num_Registro`),
  UNIQUE INDEX `NumRegistro_UNIQUE` (`Num_Registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exemplo1_Avião`.`Voo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exemplo1_Avião`.`Voo` (
  `Num_Voo` INT NOT NULL,
  `Hora_Partida` DATE NOT NULL,
  `Hora_Chegada` DATE NOT NULL,
  `Local_Partida` VARCHAR(45) NOT NULL,
  `Local_Destino` VARCHAR(45) NOT NULL,
  `Num_Piloto` INT NOT NULL,
  PRIMARY KEY (`Num_Voo`),
  INDEX `fk_Voo_Piloto_idx` (`Num_Piloto` ASC) VISIBLE,
  CONSTRAINT `fk_Voo_Piloto`
    FOREIGN KEY (`Num_Piloto`)
    REFERENCES `Exemplo1_Avião`.`Piloto` (`Num_Registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exemplo1_Avião`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exemplo1_Avião`.`Cliente` (
  `Num_Identidade` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(20) NOT NULL,
  `Endereço` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Num_Identidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Exemplo1_Avião`.`Voo_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Exemplo1_Avião`.`Voo_Cliente` (
  `Num_Voo` INT NOT NULL,
  `Num_Identidade` VARCHAR(20) NOT NULL,
  `Num_Cadeira` VARCHAR(5) NOT NULL,
  `Peso_Bagagem` FLOAT NULL,
  INDEX `fk_Voo_Cliente_Voo1_idx` (`Num_Voo` ASC) VISIBLE,
  INDEX `fk_Voo_Cliente_Cliente1_idx` (`Num_Identidade` ASC) VISIBLE,
  CONSTRAINT `fk_Voo_Cliente_Voo1`
    FOREIGN KEY (`Num_Voo`)
    REFERENCES `Exemplo1_Avião`.`Voo` (`Num_Voo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voo_Cliente_Cliente1`
    FOREIGN KEY (`Num_Identidade`)
    REFERENCES `Exemplo1_Avião`.`Cliente` (`Num_Identidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
