-- MySQL Script generated by MySQL Workbench
-- Fri Nov 10 21:42:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Empresa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Empresa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Empresa` DEFAULT CHARACTER SET utf8 ;
USE `Empresa` ;

-- -----------------------------------------------------
-- Table `Empresa`.`Empregado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa`.`Empregado` (
  `idEmpregado` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Especialização` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpregado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa`.`Projeto` (
  `idProjeto` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Empresa`.`Participacao_Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa`.`Participacao_Projeto` (
  `idEmpregado` INT NOT NULL,
  `id_Projeto` INT NOT NULL,
  `Data_Inicio` DATE NOT NULL,
  INDEX `fk_Participacao_Projeto_Empregado_idx` (`idEmpregado` ASC) VISIBLE,
  INDEX `fk_Participacao_Projeto_Projeto1_idx` (`id_Projeto` ASC) VISIBLE,
  CONSTRAINT `fk_Participacao_Projeto_Empregado`
    FOREIGN KEY (`idEmpregado`)
    REFERENCES `Empresa`.`Empregado` (`idEmpregado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participacao_Projeto_Projeto1`
    FOREIGN KEY (`id_Projeto`)
    REFERENCES `Empresa`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
